import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#3A3F32',
    paddingLeft: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2A3B1F',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 10,
    paddingTop: 35,
    zIndex: 9,
  },
  headerIcon: {
    padding: 5,
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'white',
    textAlign: 'center',
  },
  dropdownMenu: {
    position: 'absolute',
    top: 92,
    left: 10,
    right: 10,
    backgroundColor: '#4C6139',
    borderRadius: 20,
    paddingVertical: 12,
    paddingHorizontal: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
    zIndex: 8,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 15,
    marginVertical: 5,
    backgroundColor: '#5A773F',
  },
  menuText: {
    fontSize: 16,
    color: 'white',
    marginLeft: 15,
    flex: 1,
  },

  messageList: {
    flex: 1,
    marginBottom: 10,
  },
  messageContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    // Добавяме 5px разстояние между всяко съобщение
    marginBottom: 5,
  },
  myMessageContainer: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-end',
    marginRight: 10,
  },
  otherMessageContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginLeft: 10,
  },
  spacedMessages: {
    marginBottom: 10, // 10px разстояние между различни потребители
  },
  messageContent: {
    padding: 10,
    borderRadius: 15,
    backgroundColor: 'transparent',
    flexShrink: 1,
  },
  myMessage: {
    backgroundColor: '#5A773F',
    color: 'white',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 5,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 5,
    padding: 10,
    maxWidth: '70%',
  },
  otherMessage: {
    backgroundColor: '#857550',
    color: 'white',
    borderTopLeftRadius: 5,
    borderTopRightRadius: 15,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 15,
    padding: 10,
    maxWidth: '70%',
    marginLeft: 40,
  },
  messageMediaContainer: {
    marginVertical: 2,
    borderWidth: 2,
    borderColor: '#5A773F',
    borderRadius: 20,
    overflow: 'hidden',
    width: 250,
    height: 250,
    backgroundColor: 'black', // добавен черен фон
  },
  messageImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  messageVideo: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  
  messageWithProfile: {
    marginLeft: 40, // Подравняване на съобщенията с профилна снимка
  }, 
  profileIconContainer: {
    width: 0,
    height: 35,
    borderRadius: 17.5,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: -10,
    marginLeft: 10,
  },
  profileIcon: {
    width: 35,
    height: 35,
    borderRadius: 17.5,
  },
  messageText: {
    fontSize: 15,
    color: 'white',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    backgroundColor: '#2A3B1F',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 15,
    justifyContent: 'space-evenly',
  },
  input: {
    flex: 1,
    padding: 10,
    borderColor: '#5A773F',
    borderWidth: 2,
    borderRadius: 20,
    marginHorizontal: 8,
    maxWidth: '65%',
    color: 'white',
    fontSize: 14,
  },
  icon: {
    marginHorizontal: 8,
    fontSize: 22, // Намаляване на размера на иконите
  },
  iconContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 8,
  },
  voiceMessageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#857550',
    padding: 8,
    borderRadius: 15,
    marginVertical: 2,
    width: '70%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  playButton: {
    width: 25,
    height: 25,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12.5,
    backgroundColor: '#334603',
    marginRight: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
  },
  progressBar: {
    flex: 1,
    height: 4,
    backgroundColor: '#ccc',
    borderRadius: 2,
    marginHorizontal: 4,
  },
  progressIndicator: {
    height: '100%',
    backgroundColor: '#334603',
    width: '50%',
  },
  durationText: {
    fontSize: 12,
    color: 'white',
    marginLeft: 4,
  },
  fullScreenContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullScreenImage: {
    width: '100%',
    height: '80%',
  },
  fullScreenVideo: {
    width: '100%',
    height: '80%',
  },
  closeButton: {
    position: 'absolute',
    top: 40,
    right: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  optionsModalContainer: {
    width: '80%',
    backgroundColor: '#2A3B1F',
    borderRadius: 15,
    paddingVertical: 20,
    paddingHorizontal: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 10,
  },
  optionButton: {
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#5A773F',
  },
  optionButtonLast: {
    paddingVertical: 15,
  },
  optionText: {
    fontSize: 18,
    color: 'white',
    textAlign: 'center',
  },
});
